[tool.ruff]
target-version = "py38"
line-length = 120

extend-select = [
  "B",
  "C",
  "I",
  "SIM",
  "INP001",
  "W"
]

ignore = [
  "E501",
  "F401",
  "C901",
]

extend-exclude = [
  "face_detection/*.py",
]

[tool.ruff.per-file-ignores]

"models/__init__.py" = [
  "F401", # "Imported but unused"
]