
inference:
  batch_size: 1
  frame:
    h: 224
    w: 224
  model:
    wav2lip:
      checkpoint: "checkpoints/lrs3-wav2lip.pth"
    nota_wav2lip:
      checkpoint: "checkpoints/lrs3-nota-wav2lip.pth"

audio:
  num_mels: 80
  rescale: True
  rescaling_max: 0.9

  use_lws: False

  n_fft: 800  # Extra window size is filled with 0 paddings to match this parameter
  hop_size: 200  # For 16000Hz, 200 :  12.5 ms (0.0125 * sample_rate)
  win_size: 800  # For 16000Hz, 800 :  50 ms (If None, win_size :  n_fft) (0.05 * sample_rate)
  sample_rate: 16000  # 16000Hz (corresponding to librispeech) (sox --i <filename>)

  frame_shift_ms: ~

  signal_normalization: True
  allow_clipping_in_normalization: True
  symmetric_mels: True
  max_abs_value: 4.
  preemphasize: True
  preemphasis: 0.97

  # Limits
  min_level_db: -100
  ref_level_db: 20
  fmin: 55
  fmax: 7600

face:
  video_fps: 25
  img_size: 96
  mel_step_size: 16

