name: Sync to HF Space - Nota Wav2Lip
on:
  push:
    branches:
     - 'main'

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout with Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git clone https://nota-ai:$HF_TOKEN@huggingface.co/spaces/nota-ai/compressed-wav2lip hf_demo
      - name: Move asset files to other locations
        run: |
          rsync -ax --exclude ./hf_demo ./* hf_demo/
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_demo
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.comthub-actions[bot]@users.noreply.github.com"
          echo `git add . && git commit -m  "Auto-published by GitHub: https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"`
          git push --force https://nota-ai:$HF_TOKEN@huggingface.co/spaces/nota-ai/compressed-wav2lip main